name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up JDK 21
    uses: actions/setup-java@v3
    with:
      distribution: 'temurin'
      java-version: '21'

  - name: Grant execute permission for gradlew
    run: chmod +x ./gradlew

  - name: Build with Gradle
    run: ./gradlew clean build

  - name: Copy JAR file to remote server
    uses: appleboy/scp-action@v0.1.7
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.SSH_KEY }}
      port: 22
      source: "build/libs/*.jar"
      target: "/home/${{ secrets.USERNAME }}"
      strip_components: 2
      timeout: 60s

  - name: Deploy application
    uses: appleboy/ssh-action@v0.1.7
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.SSH_KEY }}
      port: 22
      timeout: 60s
      command_timeout: 5m
      debug: true
      script: |
        pkill -f 'java' || true
        cd /home/${{ secrets.USERNAME }}
        mv *.jar spring-app.jar
        nohup java -jar spring-app.jar > app.log 2>&1 &