name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Copy JAR file to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "build/libs/spring-app.jar"
          target: "/home/${{ secrets.USERNAME }}/deploy/"
          rm: true

      - name: Deploy application
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/${{ secrets.USERNAME }}/deploy
            pkill -f 'spring-app.jar' || true
            nohup java -jar spring-app.jar > app.log 2>&1 &
            sleep 5
            curl -s http://localhost:8080/actuator/health || exit 1
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
