name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Copy JAR file to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build/libs/*.jar
          remote: /home/${{ secrets.USERNAME }}/spring-app.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          port: 22

      - name: Deploy application
        uses: fifsky/ssh-action@master
        with:
          command: |
            pkill -f 'java' || true
            cd /home/${{ secrets.USERNAME }}
            ls -la
            nohup java -jar spring-app.jar > app.log 2>&1 &
            sleep 10
            ps aux | grep java
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
